import { User, AnggotaKeluarga, KasMasuk, KasKeluar, Agenda, PesertaAcara, Galeri, DocumentRecord } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'u_1',
    nama: 'Budi Sukadi Arwani',
    email: 'bowo@gmail.com',
    role: 'Administrator',
    status: 'Aktif',
  },
  {
    id: 'u_2',
    nama: 'Dewi Sukadi Arwani',
    email: 'dewi@keluarga.com',
    role: 'Bendahara',
    status: 'Aktif',
  },
  {
    id: 'u_3',
    nama: 'Aditya Sukadi Arwani',
    email: 'aditya@keluarga.com',
    role: 'Anggota',
    status: 'Aktif',
  },
];

export const SEED_ANGGOTA: AnggotaKeluarga[] = [
  // Generasi 1 (Kakek & Nenek)
  {
    id: 'A1',
    nama: 'Rustam Sukadi Arwani (Alm)',
    gender: 'Laki-laki',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '1942-04-12',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A2',
    alamat: 'Jl. Malioboro No. 45, Yogyakarta',
    telepon: '-',
    pekerjaan: 'Pensiunan PNS',
    foto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Wafat',
    tanggalWafat: '2020-11-05',
  },
  {
    id: 'A2',
    nama: 'Siti Aminah',
    gender: 'Perempuan',
    tempatLahir: 'Solo',
    tanggalLahir: '1947-08-24',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A1',
    alamat: 'Jl. Malioboro No. 45, Yogyakarta',
    telepon: '081234567800',
    pekerjaan: 'Ibu Rumah Tangga',
    foto: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },

  // Generasi 2 (Anak-anak Rustam & Siti)
  {
    id: 'A3',
    nama: 'Budi Sukadi Arwani',
    gender: 'Laki-laki',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '1970-05-15',
    ayahId: 'A1',
    ibuId: 'A2',
    pasanganId: 'A4',
    alamat: 'Jl. Kebagusan No. 12, Jakarta Selatan',
    telepon: '081234567801',
    pekerjaan: 'Manager IT',
    foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A4',
    nama: 'Rina Kartika',
    gender: 'Perempuan',
    tempatLahir: 'Bandung',
    tanggalLahir: '1973-11-02',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A3',
    alamat: 'Jl. Kebagusan No. 12, Jakarta Selatan',
    telepon: '081234567802',
    pekerjaan: 'Dosen',
    foto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A5',
    nama: 'Dewi Sukadi Arwani',
    gender: 'Perempuan',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '1974-09-21',
    ayahId: 'A1',
    ibuId: 'A2',
    pasanganId: 'A6',
    alamat: 'Sleman, D.I. Yogyakarta',
    telepon: '081234567803',
    pekerjaan: 'Wiraswasta Swasta',
    foto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A6',
    nama: 'Hendra Wijaya',
    gender: 'Laki-laki',
    tempatLahir: 'Semarang',
    tanggalLahir: '1971-03-30',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A5',
    alamat: 'Sleman, D.I. Yogyakarta',
    telepon: '081234567804',
    pekerjaan: 'Dokter Spesialis',
    foto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A7',
    nama: 'Ahmad Sukadi Arwani',
    gender: 'Laki-laki',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '1979-07-08',
    ayahId: 'A1',
    ibuId: 'A2',
    pasanganId: 'A8',
    alamat: 'Citraland, Surabaya',
    telepon: '081234567805',
    pekerjaan: 'Arsitek',
    foto: 'https://images.unsplash.com/photo-1624561172888-ac93c696e10c?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A8',
    nama: 'Sarah Lestari',
    gender: 'Perempuan',
    tempatLahir: 'Surabaya',
    tanggalLahir: '1982-12-14',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A7',
    alamat: 'Citraland, Surabaya',
    telepon: '081234567806',
    pekerjaan: 'Notaris',
    foto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },

  // Generasi 3 (Cucu-cucu)
  // Anak Budi & Rina
  {
    id: 'A9',
    nama: 'Aditya Sukadi Arwani',
    gender: 'Laki-laki',
    tempatLahir: 'Jakarta',
    tanggalLahir: '1995-02-18',
    ayahId: 'A3',
    ibuId: 'A4',
    pasanganId: 'A10',
    alamat: 'Jl. Margonda No. 101, Depok',
    telepon: '081234567808',
    pekerjaan: 'Software Engineer',
    foto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A10',
    nama: 'Amanda Putri',
    gender: 'Perempuan',
    tempatLahir: 'Bogor',
    tanggalLahir: '1997-06-25',
    ayahId: '',
    ibuId: '',
    pasanganId: 'A9',
    alamat: 'Jl. Margonda No. 101, Depok',
    telepon: '081234567809',
    pekerjaan: 'Desainer Grafis',
    foto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A11',
    nama: 'Citra Sukadi Arwani',
    gender: 'Perempuan',
    tempatLahir: 'Jakarta',
    tanggalLahir: '1999-10-05',
    ayahId: 'A3',
    ibuId: 'A4',
    pasanganId: '',
    alamat: 'Jl. Kebagusan No. 12, Jakarta Selatan',
    telepon: '081234567810',
    pekerjaan: 'Akuntan publik',
    foto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  // Anak Dewi & Hendra
  {
    id: 'A12',
    nama: 'Rio Wijaya',
    gender: 'Laki-laki',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '2001-01-12',
    ayahId: 'A6',
    ibuId: 'A5',
    pasanganId: '',
    alamat: 'Condongcatur, Sleman',
    telepon: '081234567811',
    pekerjaan: 'Mahasiswa Kedokteran',
    foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  {
    id: 'A13',
    nama: 'Sekar Wijaya',
    gender: 'Perempuan',
    tempatLahir: 'Yogyakarta',
    tanggalLahir: '2004-08-29',
    ayahId: 'A6',
    ibuId: 'A5',
    pasanganId: '',
    alamat: 'Condongcatur, Sleman',
    telepon: '081234567812',
    pekerjaan: 'Pelajar SMA',
    foto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },
  // Anak Ahmad & Sarah
  {
    id: 'A14',
    nama: 'Kevin Sukadi Arwani',
    gender: 'Laki-laki',
    tempatLahir: 'Surabaya',
    tanggalLahir: '2011-04-14',
    ayahId: 'A7',
    ibuId: 'A8',
    pasanganId: '',
    alamat: 'Citraland, Surabaya',
    telepon: '081234567813',
    pekerjaan: 'Siswa SMP',
    foto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  },

  // Generasi 4 (Cicit)
  // Anak Aditya & Amanda
  {
    id: 'A15',
    nama: 'Dian Sukadi Arwani',
    gender: 'Perempuan',
    tempatLahir: 'Depok',
    tanggalLahir: '2023-01-10',
    ayahId: 'A9',
    ibuId: 'A10',
    pasanganId: '',
    alamat: 'Jl. Margonda No. 101, Depok',
    telepon: '-',
    pekerjaan: 'Balita',
    foto: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=150&h=150&q=80',
    statusHidup: 'Hidup',
  }
];

export const SEED_KAS_MASUK: KasMasuk[] = [
  {
    id: 'KM_1',
    tanggal: '2026-01-05',
    kategori: 'Iuran Bulanan',
    sumber: 'Budi Sukadi Arwani',
    nominal: 500000,
    keterangan: 'Iuran semester 1 keluarga Budi',
    bukti: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'KM_2',
    tanggal: '2026-01-08',
    kategori: 'Iuran Bulanan',
    sumber: 'Dewi Sukadi Arwani',
    nominal: 500000,
    keterangan: 'Iuran semester 1 keluarga Dewi',
    bukti: '',
  },
  {
    id: 'KM_3',
    tanggal: '2026-01-12',
    kategori: 'Iuran Bulanan',
    sumber: 'Ahmad Sukadi Arwani',
    nominal: 500000,
    keterangan: 'Iuran semester 1 keluarga Ahmad',
    bukti: '',
  },
  {
    id: 'KM_4',
    tanggal: '2026-02-14',
    kategori: 'Sumbangan',
    sumber: 'Hendra Wijaya',
    nominal: 2000000,
    keterangan: 'Donasi tambahan untuk perbaikan makam kakek',
    bukti: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'KM_5',
    tanggal: '2026-04-10',
    kategori: 'Sumbangan',
    sumber: 'Siti Aminah',
    nominal: 1000000,
    keterangan: 'Donasi syukuran keluarga',
    bukti: '',
  },
  {
    id: 'KM_6',
    tanggal: '2026-05-20',
    kategori: 'Iuran Bulanan',
    sumber: 'Aditya Sukadi Arwani',
    nominal: 250000,
    keterangan: 'Iuran semester 1 keluarga Aditya',
    bukti: '',
  }
];

export const SEED_KAS_KELUAR: KasKeluar[] = [
  {
    id: 'KK_1',
    tanggal: '2026-01-20',
    kategori: 'Santunan',
    nominal: 750000,
    keterangan: 'Santunan kerabat sakit di kediri',
    bukti: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'KK_2',
    tanggal: '2026-02-25',
    kategori: 'Operasional',
    nominal: 1500000,
    keterangan: 'Renovasi nisan Almarhum Rustam Sukadi Arwani',
    bukti: '',
  },
  {
    id: 'KK_3',
    tanggal: '2026-04-05',
    kategori: 'Arisan',
    nominal: 500000,
    keterangan: 'Biaya konsumsi pertemuan arisan triwulan',
    bukti: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'KK_4',
    tanggal: '2026-05-15',
    kategori: 'Konsumsi',
    nominal: 300000,
    keterangan: 'Pembelian kue hantaran Ramadhan',
    bukti: '',
  }
];

export const SEED_AGENDA: Agenda[] = [
  {
    id: 'AG_1',
    namaAcara: 'Arisan & Silaturahmi Triwulan Keluarga',
    tanggal: '2026-07-12',
    waktu: '10:00',
    lokasi: 'Jl. Malioboro No. 45, Yogyakarta (Rumah Ibu Siti Aminah)',
    deskripsi: 'Pertemuan rutin silarutahmi keluarga besar Sukadi Arwani, arisan triwulanan, sekaligus makan siang bersama & pembagian kaos keluarga.',
    penanggungJawab: 'Dewi Sukadi Arwani',
  },
  {
    id: 'AG_2',
    namaAcara: 'Peringatan 6 Tahun Wafatnya Kakek Rustam',
    tanggal: '2026-11-05',
    waktu: '18:30',
    lokasi: 'Jl. Kebagusan No. 12, Jakarta Selatan (Rumah Budi Sukadi Arwani) & Zoom',
    deskripsi: 'Tahlilan bersama, doa, dan sedekah keluarga memperingati wafatnya Kakek tercinta Rustam Sukadi Arwani.',
    penanggungJawab: 'Budi Sukadi Arwani',
  },
  {
    id: 'AG_3',
    namaAcara: 'Liburan Akhir Tahun Bersama ke Bali',
    tanggal: '2026-12-25',
    waktu: '08:00',
    lokasi: 'Nusa Dua, Bali',
    deskripsi: 'Liburan tahunan keluarga besar, menginap bersama di Villa Seminyak and acara BBQ silsilah keluarga.',
    penanggungJawab: 'Ahmad Sukadi Arwani',
  }
];

export const SEED_PESERTA: PesertaAcara[] = [
  // Agenda 1
  { id: 'P1', agendaId: 'AG_1', anggotaId: 'A2', anggotaNama: 'Siti Aminah', statusHadir: 'Hadir' },
  { id: 'P2', agendaId: 'AG_1', anggotaId: 'A3', anggotaNama: 'Budi Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P3', agendaId: 'AG_1', anggotaId: 'A4', anggotaNama: 'Rina Kartika', statusHadir: 'Hadir' },
  { id: 'P4', agendaId: 'AG_1', anggotaId: 'A5', anggotaNama: 'Dewi Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P5', agendaId: 'AG_1', anggotaId: 'A6', anggotaNama: 'Hendra Wijaya', statusHadir: 'Hadir' },
  { id: 'P6', agendaId: 'AG_1', anggotaId: 'A7', anggotaNama: 'Ahmad Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P7', agendaId: 'AG_1', anggotaId: 'A8', anggotaNama: 'Sarah Lestari', statusHadir: 'Hadir' },
  { id: 'P8', agendaId: 'AG_1', anggotaId: 'A9', anggotaNama: 'Aditya Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P9', agendaId: 'AG_1', anggotaId: 'A10', anggotaNama: 'Amanda Putri', statusHadir: 'Hadir' },
  { id: 'P10', agendaId: 'AG_1', anggotaId: 'A11', anggotaNama: 'Citra Sukadi Arwani', statusHadir: 'Absen' },
  { id: 'P11', agendaId: 'AG_1', anggotaId: 'A12', anggotaNama: 'Rio Wijaya', statusHadir: 'Hadir' },
  { id: 'P12', agendaId: 'AG_1', anggotaId: 'A13', anggotaNama: 'Sekar Wijaya', statusHadir: 'Hadir' },
  { id: 'P13', agendaId: 'AG_1', anggotaId: 'A14', anggotaNama: 'Kevin Sukadi Arwani', statusHadir: 'Ragu-ragu' },
  { id: 'P14', agendaId: 'AG_1', anggotaId: 'A15', anggotaNama: 'Dian Sukadi Arwani', statusHadir: 'Hadir' },

  // Agenda 2
  { id: 'P15', agendaId: 'AG_2', anggotaId: 'A2', anggotaNama: 'Siti Aminah', statusHadir: 'Hadir' },
  { id: 'P16', agendaId: 'AG_2', anggotaId: 'A3', anggotaNama: 'Budi Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P17', agendaId: 'AG_2', anggotaId: 'A5', anggotaNama: 'Dewi Sukadi Arwani', statusHadir: 'Belum RSVP' },
  { id: 'P18', agendaId: 'AG_2', anggotaId: 'A7', anggotaNama: 'Ahmad Sukadi Arwani', statusHadir: 'Hadir' },
  { id: 'P19', agendaId: 'AG_2', anggotaId: 'A9', anggotaNama: 'Aditya Sukadi Arwani', statusHadir: 'Belum RSVP' }
];

export const SEED_GALERI: Galeri[] = [
  {
    id: 'G1',
    agendaId: 'AG_1',
    agendaNama: 'Arisan & Silaturahmi Triwulan Keluarga',
    judul: 'Foto Bersama Keluarga Besar 2025',
    fileUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=600&q=80',
    fileType: 'image',
    uploader: 'Aditya Sukadi Arwani',
    tanggalUpload: '2025-06-15',
  },
  {
    id: 'G2',
    agendaId: 'AG_1',
    agendaNama: 'Arisan & Silaturahmi Triwulan Keluarga',
    judul: 'Makan Siang Arisan Syahdu',
    fileUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=600&q=80',
    fileType: 'image',
    uploader: 'Amanda Putri',
    tanggalUpload: '2025-06-15',
  },
  {
    id: 'G3',
    agendaId: 'AG_1',
    agendaNama: 'Arisan & Silaturahmi Triwulan Keluarga',
    judul: 'Cucu dan Cicit Bermain Bersama',
    fileUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80',
    fileType: 'image',
    uploader: 'Dewi Sukadi Arwani',
    tanggalUpload: '2025-06-16',
  }
];

export const SEED_DOKUMEN: DocumentRecord[] = [
  {
    id: 'D1',
    namaDokumen: 'Laporan_Keuangan_Keluarga_2025.pdf',
    kategori: 'Laporan Keuangan',
    fileUrl: '#',
    uploader: 'Dewi Sukadi Arwani',
    tanggalUpload: '2025-12-31',
  },
  {
    id: 'D2',
    namaDokumen: 'Notulen_Rapat_Liburan_Bali_2026.pdf',
    kategori: 'Notulen Semenjak',
    fileUrl: '#',
    uploader: 'Budi Sukadi Arwani',
    tanggalUpload: '2026-04-12',
  },
  {
    id: 'D3',
    namaDokumen: 'Buku_Silsilah_Silsilah_Rustam_Sukadi_Arwani_v2.pdf',
    kategori: 'Buku Silsilah',
    fileUrl: '#',
    uploader: 'Aditya Sukadi Arwani',
    tanggalUpload: '2026-05-01',
  }
];
